### ISSUE TITLE
hi，can i ask you some questions

### ISSUE THREAD

**Issue by ownerowner** [maxwell-martin/netflix-movies-scraper#4]
some videos has an  sample aes encryption，i dont know how to reslove it by myself because i am not majored with computer，i get a m3u8file ，the content is like this:
method:sample aes ，url＝skd://entry—13hgcz24z ， keyformat＝com.apple.streamingkeydelivery. 
Can you do me a favor.thanks very much

**Comment by maxwell-martin** [comment]
Can you please rephrase your question? I do not understand what you are asking.

**Comment by ownerowner** [comment]
> Can you please rephrase your question? I do not understand what you are asking.
i am so sorry，i mean i wanna download the video encrypted with sample—aes method ，i only get a index.m3u8 ，i couldnt download the video  unless decrypting the method，so i need your help

**Comment by ownerowner** [comment]
> Can you please rephrase your question? I do not understand what you are asking.

i am so sorry，i mean i wanna download the video encrypted with sample—aes method ，i only get a index.m3u8 ，i couldnt download the video unless decrypting the method，so i need your help

**Comment by maxwell-martin** [comment]
This project was not created to download videos. It gets a list of movies from Netflix with corresponding ratings for each movie and exports the data as a CSV file.
